#!/usr/bin/env bash
# This script displays numbers and associated messages based on the loop iteration

num=1
while [ $num -lt 21 ]; do
      echo $num
      case $num in
      4) echo "bad luck from China"
      ;;
      9) echo "bad luck from Japan"
      ;;
      17) echo "bad luck from Italy"
      ;;
      esac
      num=$((num+1))
done
